'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

	'''<summary>
	'''updTM control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updTM As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''PageUpdateProgress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PageUpdateProgress2 As Global.System.Web.UI.UpdateProgress

	'''<summary>
	'''lnkAnnounce control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAnnounce As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkSupport As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkAccnt control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAccnt As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkAType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAType As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkData As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lbleMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''panAType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAType As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlAType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtAType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAType As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''chkFSales control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFSales As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRSales control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRSales As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkData As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFProd As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRProd As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkAnnounce control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkAnnounce As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFCompete As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRCompete As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkContent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkContent As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFStocks As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRStocks As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFInventory As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRInventory As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRTM control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRTM As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFVisual control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFVisual As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRVisual control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRVisual As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFTrade control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFTrade As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRTrade control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRTrade As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkFSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkFSupport As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''chkRSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents chkRSupport As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''panData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panData As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''btnHGeneral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHGeneral As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSupport As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHStore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHStore As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHCCAC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHCCAC As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHCompete As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHReport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHReport As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnPopDay control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPopDay As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnPopWeek control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPopWeek As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnHSA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnHSA As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''txtSA control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSA As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnProd As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnBrand As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnItem As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnModel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCap As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnVariant As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAction As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDealer As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnStore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnStore As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCity As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnProv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnProv As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnRegion As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnQuestion As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCBrand As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCCap As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubject As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnTarget control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTarget As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''panProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panProd As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtProd As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbAProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbAProd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMProd As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstProd As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panBrand As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlBProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlBProd As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtBrand As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbABrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbABrand As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMBrand As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''grdBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdBrand As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panModel As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlMProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMProd As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlMBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMBrand As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtModel As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnMCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnMCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnMCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnMCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdModel As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panItem As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddliProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddliProd As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddliBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddliBrand As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtItem As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtLCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLCode As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDesc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDesc As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddliModel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddliModel As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddliVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddliVariant As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddliCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddliCap As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnICreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnICreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnICancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnICancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdItem control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdItem As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panCap As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlCProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCProd As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCBrand As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCap As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnCapCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCapCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCapCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCapCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdCap As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panVariant As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtVariant As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbAVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbAVariant As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMVariant As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstVariant control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstVariant As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panDealer As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDealer As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbADealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbADealer As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMDealer As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstDealer As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panLoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panLoc As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtLoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLoc As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbALoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbALoc As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMLoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMLoc As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstLoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstLoc As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panStore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panStore As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtSC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSC As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddlSCDealer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSCDealer As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlSCLoc control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSCLoc As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlSCRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSCRegion As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtParent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtParent As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtChild1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtChild1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtChild2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtChild2 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtChild3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtChild3 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSCCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSCCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSCCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSCCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdStore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdStore As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panCity As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlCRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCRegion As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlCProv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCProv As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnCCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnCCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdCity As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panProv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panProv As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlPRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlPRegion As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtProvince control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtProvince As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnPCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnPCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdProv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdProv As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panRegion As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtRegion As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbARegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbARegion As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMRegion As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstRegion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstRegion As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAction As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAction As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbAAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbAAction As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMAction As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstAction control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstAction As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panQuestion As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQuestion As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbAQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbAQuestion As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMQuestion As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstQuestion control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstQuestion As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panCBrand As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCBrand As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbACBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbACBrand As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMCBrand As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstCBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstCBrand As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panCCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panCCap As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtCCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtCCap As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbACCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbACCap As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMCCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMCCap As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstCCap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstCCap As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panSubject As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''imbASubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbASubject As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbMSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbMSubject As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''lstSubject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lstSubject As Global.System.Web.UI.WebControls.ListBox

	'''<summary>
	'''panTarget control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panTarget As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''ddlTProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTProd As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlTWeek control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlTWeek As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtWeek control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtWeek As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnTWCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTWCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnTWCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTWCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ddlMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMonth As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlMYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMYear As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMonth As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnTMCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTMCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnTMCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTMCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ddlYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlYear As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnTYCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTYCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnTYCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnTYCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdTarget control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdTarget As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''pnlPopDay control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlPopDay As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''pnlPopWeek control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlPopWeek As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''panAnnounce control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAnnounce As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''panAData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAData As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''imgPic control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imgPic As Global.System.Web.UI.WebControls.Image

	'''<summary>
	'''imbPicRemove control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbPicRemove As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''txtTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtIntro control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtIntro As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtStory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtStory As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''rblPublish control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rblPublish As Global.System.Web.UI.WebControls.RadioButtonList

	'''<summary>
	'''lblCDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblCBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblCBy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''iMDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents iMDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblMDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMDate As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''iMBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents iMBy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblMBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblMBy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lbleMsg1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg1 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnModify control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnModify As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnACancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnACancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnAddPic control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAddPic As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnACreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnACreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdAnnounce control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdAnnounce As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panSupport As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''panSData control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panSData As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblTNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblTNo As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblDCreated control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblDCreated As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblSCBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSCBy As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblSubj control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSubj As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblComment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblComment As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''panReply control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panReply As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtReply control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtReply As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''rblSStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents rblSStat As Global.System.Web.UI.WebControls.RadioButtonList

	'''<summary>
	'''lbleMsg4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnAllSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAllSupport As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''grdSTrans control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdSTrans As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panSGrid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panSGrid As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdSupport control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdSupport As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAccount As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''btnAEmp control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAEmp As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnUnlock control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnUnlock As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnReactivate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnReactivate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''panUsers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panUsers As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''panUSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panUSearch As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ddlFType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlFStatus control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFStatus As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''grdAccount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdAccount As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panDeactivate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panDeactivate As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdDeactivate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdDeactivate As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panUnlock control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panUnlock As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdUnlock control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdUnlock As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panAEmp control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panAEmp As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''txtFname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFname As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMname As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtLname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLname As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtAAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAAdd As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtAContact control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAContact As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtAEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtAUname control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtAUname As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddlAAType control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAAType As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlLStat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlLStat As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''ddlFC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlFC As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lblFC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblFC As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''ddlSFC control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSFC As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''txtADouble control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtADouble As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''ddlStore control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlStore As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''lbleMsg3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''btnAcModify control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAcModify As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnAcCancel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAcCancel As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnAcReset control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnAcReset As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnDeactivate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnDeactivate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''sqlDS_Deactivate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Deactivate As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Unlock control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Unlock As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Announce control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Announce As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Account control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Account As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Brand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Brand As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Item control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Item As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Model control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Model As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Cap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Cap As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_City control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_City As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Prov control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Prov As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Store control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Store As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Support control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Support As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_STrans control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_STrans As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Target control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Target As Global.System.Web.UI.WebControls.SqlDataSource
End Class
