'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class populateday

	'''<summary>
	'''pnlAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAdd As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''a_wDay control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wDay As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_weekID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_weekID As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_hidden control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_hidden As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''submit_add control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submit_add As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''i_wDay control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wDay As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_weekID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_weekID As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_hidden control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_hidden As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''submit_edit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submit_edit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDelete As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''litWDTable control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litWDTable As Global.System.Web.UI.WebControls.Literal
End Class
