'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class populateweek

	'''<summary>
	'''pnlAdd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlAdd As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''a_wFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wFrom As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_wTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wTo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_weekCoverage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_weekCoverage As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_wYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wYear As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_wMonthID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wMonthID As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_wNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_wNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''a_hidden control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents a_hidden As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''submit_add control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submit_add As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlEdit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''i_wFrom control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wFrom As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_wTo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wTo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_weekCoverage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_weekCoverage As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_wYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wYear As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_wMonthID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wMonthID As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_wNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_wNo As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''i_hidden control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents i_hidden As Global.System.Web.UI.WebControls.HiddenField

	'''<summary>
	'''submit_edit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submit_edit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''pnlDelete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pnlDelete As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''litWkTable control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents litWkTable As Global.System.Web.UI.WebControls.Literal
End Class
