'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Forgot_Password

	'''<summary>
	'''lbleMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''p_email_validator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents p_email_validator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''p_email_reg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents p_email_reg As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''liame control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents liame As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''send_email control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents send_email As Global.System.Web.UI.WebControls.Button
End Class
