'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HomePage

    '''<summary>
    '''updClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updClient As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imbSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbSales As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbReport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbSupport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbSupport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbComm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbComm As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''grdAnnounce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAnnounce As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdPerf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPerf As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sqlDS_Announce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Announce As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDS_Perf1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Perf1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDS_Perf2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Perf2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDS_High control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_High As Global.System.Web.UI.WebControls.SqlDataSource
End Class
