'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Sales

	'''<summary>
	'''updTM control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updTM As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''PageUpdateProgress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PageUpdateProgress2 As Global.System.Web.UI.UpdateProgress

	'''<summary>
	'''lProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lProd As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lnkProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkProd As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lCompete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lnkCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkCompete As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lStocks As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lnkStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkStocks As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lInventory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lnkInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkInventory As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''ddlWeek control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlWeek As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''btnCreate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCreate As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnSubmit control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnUpload control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''lbleMsg control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lbleMsg As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''imbYes control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbYes As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''imbNo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbNo As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''panInfo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panInfo As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''lblifProd control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblifProd As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblifBrand control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblifBrand As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''imbClose control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents imbClose As Global.System.Web.UI.WebControls.ImageButton

	'''<summary>
	'''grdInfo control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdInfo As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panSales control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panSales As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdSales control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdSales As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panCompete control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panCompete As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdCompetitor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdCompetitor As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panStocks As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdStocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdStocks As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''panInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents panInventory As Global.System.Web.UI.WebControls.Panel

	'''<summary>
	'''grdInventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents grdInventory As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''sqlDS_Info control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Info As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Sales control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Sales As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Competitor control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Competitor As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Stocks control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Stocks As Global.System.Web.UI.WebControls.SqlDataSource

	'''<summary>
	'''sqlDS_Inventory control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents sqlDS_Inventory As Global.System.Web.UI.WebControls.SqlDataSource
End Class
